config/routes.rb
Rails.application.routes.draw do
  get 'pages/index'

  resources :ideas

  devise_for :users, controllers: {registrations: "users/registrations", sessions: "users/sessions", passwords: "users/passwords"}, skip: [:sessions, :registrations]

  root 'pages#index'

  
  devise_scope :user do
    get    "login"   => "users/sessions#new",         as: :new_user_session
    post   "login"   => "users/sessions#create",      as: :user_session
    delete "signout" => "users/sessions#destroy",     as: :destroy_user_session
    
    get    "signup"  => "users/registrations#new",    as: :new_user_registration
    post   "signup"  => "users/registrations#create", as: :user_registration
    put    "signup"  => "users/registrations#update", as: :update_user_registration
    get    "account" => "users/registrations#edit",   as: :edit_user_registration
  end

end

app/models/idea.rb
class Idea < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
        :recoverable, :rememberable, :trackable, :validatable
  attr_accessor :login
  
  #->Prelang (user_login:devise/username_login_support)
  def self.find_first_by_auth_conditions(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions).where(["lower(username) = :value OR lower(email) = :value", {value: login.downcase}]).first
    else
      where(conditions).first
    end
  end


  devise authentication_keys: [:login]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  #->Prelang (user_login:devise)
  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up)        { |u| u.permit(:username, :email, :password, :password_confirmation, :remember_me) }
    devise_parameter_sanitizer.for(:sign_in)        { |u| u.permit(:login, :username, :email, :password, :remember_me) }
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:username, :email, :password, :password_confirmation, :current_password) }
  end


  private
  
  #-> Prelang (user_login:devise)
  def require_user_signed_in
    unless user_signed_in?

      # If the user came from a page, we can send them back.  Otherwise, send
      # them to the root path.
      if request.env['HTTP_REFERER']
        fallback_redirect = :back
      elsif defined?(root_path)
        fallback_redirect = root_path
      else
        fallback_redirect = "/"
      end

      redirect_to fallback_redirect, flash: {error: "You must be signed in to view this page."}
    end
  end

end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController

  #->Prelang (scaffolding:rails/scope_to_user)
  before_filter :require_user_signed_in, only: [:new, :edit, :create, :update, :destroy]

  before_action :set_idea, only: [:show, :edit, :update, :destroy]

  # GET /ideas
  # GET /ideas.json
  def index
    @ideas = Idea.all
  end

  # GET /ideas/1
  # GET /ideas/1.json
  def show
  end

  # GET /ideas/new
  def new
    @idea = Idea.new
  end

  # GET /ideas/1/edit
  def edit
  end

  # POST /ideas
  # POST /ideas.json
  def create
    @idea = Idea.new(idea_params)
    @idea.user = current_user

    respond_to do |format|
      if @idea.save
        format.html { redirect_to @idea, notice: 'Idea was successfully created.' }
        format.json { render :show, status: :created, location: @idea }
      else
        format.html { render :new }
        format.json { render json: @idea.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ideas/1
  # PATCH/PUT /ideas/1.json
  def update
    respond_to do |format|
      if @idea.update(idea_params)
        format.html { redirect_to @idea, notice: 'Idea was successfully updated.' }
        format.json { render :show, status: :ok, location: @idea }
      else
        format.html { render :edit }
        format.json { render json: @idea.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ideas/1
  # DELETE /ideas/1.json
  def destroy
    @idea.destroy
    respond_to do |format|
      format.html { redirect_to ideas_url, notice: 'Idea was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_idea
      @idea = Idea.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def idea_params
      params.require(:idea).permit(:idea_name, :description, :customer, :problem, :business_model, :i_have_experience_in_this_field, :i_am_passionate_in_this_field, :i_have_hobbies_that_are_related_to_this_field, :rank, :enthusiasm, :user_id)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  include ApplicationHelper

  def new
    super
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  include ApplicationHelper

  def create
    super
  end

  def new
    super
  end

  def edit
    super
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  include ApplicationHelper

  def create
    super
  end

  def new
    super
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ideas_helper.rb
module IdeasHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/elements/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse-1">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <%= link_to "My Application", defined?(root_path) ? root_path : "#", class: "navbar-brand" %>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse" id="navbar-collapse-1">
    <ul class="nav navbar-nav">
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <% if defined?(Devise) %>
        <% if user_signed_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Account <b class="caret"></b></a>
            <ul class="dropdown-menu">
              <li><%= link_to "Edit Account", edit_user_registration_path %></li>
              <li class="divider"></li>
              <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Login", new_user_session_path %></li>
          <li><%= link_to "Sign Up", new_user_registration_path %></li>
        <% end %>
      <% end %>
    </ul>
  </div><!-- /.navbar-collapse -->
</nav>

app/views/ideas/_form.html.erb
<%= form_for @idea, :html => { :class => 'form-horizontal form-model' } do |f| %>
  <div class="form-group">
    <%= f.label :idea_name, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :idea_name, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :description, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_area :description, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :customer, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_area :customer, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :problem, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_area :problem, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :business_model, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_area :business_model, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :i_have_experience_in_this_field, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.check_box :i_have_experience_in_this_field, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :i_am_passionate_in_this_field, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.check_box :i_am_passionate_in_this_field, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :i_have_hobbies_that_are_related_to_this_field, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.check_box :i_have_hobbies_that_are_related_to_this_field, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :rank, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.number_field :rank, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :enthusiasm, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.number_field :enthusiasm, :class => 'text-field form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class='col-md-offset-2 col-md-10'>
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                  ideas_path, :class => 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/ideas/edit.html.erb
<%- model_class = Idea -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => Idea %></h1>
</div>
<%= render :partial => 'form' %>

app/views/ideas/index.html.erb
<%- model_class = Idea -%>
<div class="page-header">
  <h1><%=t '.title', :default => Idea %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th><%= model_class.human_attribute_name(:idea_name) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <th><%= model_class.human_attribute_name(:customer) %></th>
      <th><%= model_class.human_attribute_name(:problem) %></th>
      <th><%= model_class.human_attribute_name(:business_model) %></th>
      <th><%= model_class.human_attribute_name(:i_have_experience_in_this_field) %></th>
      <th><%= model_class.human_attribute_name(:i_am_passionate_in_this_field) %></th>
      <th><%= model_class.human_attribute_name(:i_have_hobbies_that_are_related_to_this_field) %></th>
      <th><%= model_class.human_attribute_name(:rank) %></th>
      <th><%= model_class.human_attribute_name(:enthusiasm) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @ideas.each do |idea| %>
      <tr>
        <td><%= idea.id %></td>
        <td><%= idea.idea_name %></td>
        <td><%= idea.description %></td>
        <td><%= idea.customer %></td>
        <td><%= idea.problem %></td>
        <td><%= idea.business_model %></td>
        <td><%= idea.i_have_experience_in_this_field %></td>
        <td><%= idea.i_am_passionate_in_this_field %></td>
        <td><%= idea.i_have_hobbies_that_are_related_to_this_field %></td>
        <td><%= idea.rank %></td>
        <td><%= idea.enthusiasm %></td>
        <td><%=l idea.created_at, format: :long %></td>
        <td>
          <%= link_to idea_path(idea), :class => 'btn btn-xs', :title => "#{ t('.show', :default => t('helpers.links.show')) }" do %>
            <%= glyph 'info-sign' %>
            <%= glyph 'pencil' %>
          <%- end -%>
          <%= link_to idea_path(idea), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs', :title => "#{ t('.destroy', :default => t('helpers.links.destroy')) }" do %>
            <%= glyph 'remove' %>
          <%- end -%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_idea_path,
            :class => 'btn btn-primary' %>

app/views/ideas/new.html.erb
<%- model_class = Idea -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => Idea %></h1>
</div>
<%= render :partial => 'form' %>

app/views/ideas/show.html.erb
<%- model_class = Idea -%>
<div class="page-header">
  <h1><%=t '.title', :default => Idea %></h1>
</div>

<div class="fieldset">
  <dl>
      <dt class="label label-default"><%= model_class.human_attribute_name(:idea_name) %></dt>
      <dd><pre class="prettyprint"><%= @idea.idea_name %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:description) %></dt>
      <dd><pre class="prettyprint"><%= @idea.description %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:customer) %></dt>
      <dd><pre class="prettyprint"><%= @idea.customer %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:problem) %></dt>
      <dd><pre class="prettyprint"><%= @idea.problem %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:business_model) %></dt>
      <dd><pre class="prettyprint"><%= @idea.business_model %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:i_have_experience_in_this_field) %></dt>
      <dd><pre class="prettyprint"><%= @idea.i_have_experience_in_this_field %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:i_am_passionate_in_this_field) %></dt>
      <dd><pre class="prettyprint"><%= @idea.i_am_passionate_in_this_field %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:i_have_hobbies_that_are_related_to_this_field) %></dt>
      <dd><pre class="prettyprint"><%= @idea.i_have_hobbies_that_are_related_to_this_field %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:rank) %></dt>
      <dd><pre class="prettyprint"><%= @idea.rank %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:enthusiasm) %></dt>
      <dd><pre class="prettyprint"><%= @idea.enthusiasm %></pre></dd>
  </dl>
</div>

<div class="form-group">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              ideas_path, :class => 'btn btn-default'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_idea_path(@idea), :class => 'btn btn-default' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              idea_path(@idea),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>IdeaTracking</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
<meta name="viewport" content="width=device-width, initial-scale=1"/></head>
<body>
<%= render partial: "elements/navbar" %>
<%= bootstrap_flash %>


<%= yield %>

</body>
</html>

app/views/pages/index.html.erb
<h1>Pages#index</h1>
<p>Find me in app/views/pages/index.html.erb</p>